name: Build Master Release
on: [push, workflow_dispatch]
jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Linux Library
        run: cargo build --release
      - name: Upload Linux Library
        uses: actions/upload-artifact@v4
        with:
          name: linux_so
          path: target/release/libpixelbuster.so
      - name: Build Linux Binary
        run: cargo build --release --features=gui; cp target/release/gui pixelbuster_gui
      - name: Upload Linux Binary
        uses: actions/upload-artifact@v4
        with:
          name: linux_binary
          path: pixelbuster_gui
  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build MacOS Library
        run: cargo build --release
      - name: Upload MacOS Library
        uses: actions/upload-artifact@v4
        with:
          name: macos_dylib
          path: target/release/libpixelbuster.dylib
      - name: Build MacOS Binary
        run: cargo build --release --features=gui; cp target/release/gui pixelbuster_gui
      - name: Upload MacOS Binary
        uses: actions/upload-artifact@v4
        with:
          name: macos_binary
          path: pixelbuster_gui
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Windows Library
        run: cargo build --release
      - name: Upload Windows Library
        uses: actions/upload-artifact@v4
        with:
          name: windows_dll
          path: target/release/pixelbuster.dll
      - name: Build Windows Binary
        run: cargo build --release --features=gui; cp target/release/gui.exe pixelbuster_gui.exe
      - name: Upload Windows Binary
        uses: actions/upload-artifact@v4
        with:
          name: windows_exe
          path: pixelbuster_gui.exe
